apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bt-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: bt-agent
  template:
    metadata:
      labels:
        app: bt-agent
    spec:
      containers:
      - name: bt-agent
        image: mirrorcask/bt-agent:v1.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 2030
        env:
        - name: METASERVICE_URL
          value: "http://metadata-service:8080"
        - name: TRACKER_ANNOUNCE_URL
          value: "http://chihaya-service:6969/announce"
        - name: BT_DIR
          value: "/var/lib/bt-agent"
        - name: BLOB_DIR
          value: "/var/lib/containerd/io.containerd.content.v1.content/blobs/sha256"
        - name: REGISTRY_URL
          value: "registry-1.docker.io"
        volumeMounts:
        - name: data
          mountPath: /var/lib
      volumes:
      - name: data
        hostPath:
          path: /var/lib
          type: DirectoryOrCreate